markdown: kramdown
highlighter: rouge
auto: true
permalink: /blog/:year/:month/:day/:title
paginate: 10 # pagination basted on number of posts
server: true
excerpt_separator: <!--more-->
duoshuo_shortname:  xiaoyuze88
url: http://xiaoyuze88.github.io
future: true
#url: http://localhost:4000
# lsi: true