markdown: rdiscount
pygments: true
auto: true
permalink: /blog/:year/:month/:day/:title
paginate: 10 # pagination basted on number of posts
pygments: true
server: true
excerpt_separator: <!--more-->
duoshuo_shortname:  xiaoyuze88
url: http://xiaoyuze88.github.io
lsi: true